import * as PhaserBox2D from "phaser-box2d/dist/PhaserBox2D.js";

export const {
	AddSpriteToWorld,
	CreateWorld,
	DYNAMIC,
	b2BodyType,
	SetWorldScale,
	UpdateWorldSprites,
	WorldStep,
	b2CreateBody,
	b2CreatePolygonShape,
	b2DefaultBodyDef,
	b2DefaultShapeDef,
	b2DefaultWorldDef,
	b2ComputeHull,
	b2MakeOffsetPolygon,
	b2MakeRot,
	b2MakeBox,
	b2DebugDraw,
	b2Transform,
	b2Vec2,
	pxm,
	pxmVec2,
	b2World_Draw,
} = PhaserBox2D;