export type b2WorldId = {
	index1: number;
	revision: number;
};

export const AddSpriteToWorld: any;
export const RemoveSpriteFromWorld: any;
export const CreateWorld: any;
export const DYNAMIC: number;
export const b2BodyType: {
	b2_staticBody: 0;
	b2_kinematicBody: 1;
	b2_dynamicBody: 2;
	b2_bodyTypeCount: 3;
};
export const SetWorldScale: any;
export const UpdateWorldSprites: any;
export const WorldStep: any;
export const b2CreateBody: any;
export const b2DestroyBody: any;
export const b2CreateCircleShape: any;
export const b2DestroyShape: any;
export const b2CreatePolygonShape: any;
export const b2DefaultBodyDef: any;
export const b2DefaultShapeDef: any;
export const b2DefaultWorldDef: any;
export const b2DefaultWeldJointDef: any;
export const b2ComputeHull: any;
export const b2MakeOffsetPolygon: any;
export const b2MakeRot: any;
export const b2MakeBox: any;
export const b2DebugDraw: any;
export const b2Transform: any;
export const b2Circle: any;
export const b2Body_SetTransform: any;
export const b2Body_GetPosition: any;
export const b2Body_SetLinearVelocity: any;
export const b2Body_SetAngularVelocity: any;
export const b2Body_GetLocalPoint: any;
export const b2Body_SetType: any;
export const b2CreateWeldJoint: any;
export const b2DestroyJoint: any;
export const b2Vec2: any;
export const pxm: any;
export const pxmVec2: any;
export const b2World_Draw: any;