import * as PhaserBox2D from "phaser-box2d/dist/PhaserBox2D.js";
import * as PhaserBox2DDebug from "phaser-box2d/dist/PhaserBox2D-Debug.js";

export const {
	AddSpriteToWorld,
	RemoveSpriteFromWorld,
	CreateWorld,
	DYNAMIC,
	b2BodyType,
	SetWorldScale,
	UpdateWorldSprites,
	WorldStep,
	b2CreateBody,
	b2DestroyBody,
	b2CreateCircleShape,
	b2DestroyShape,
	b2Shape_SetCircle,
	b2CreatePolygonShape,
	b2DefaultBodyDef,
	b2DefaultShapeDef,
	b2DefaultWorldDef,
	b2DefaultWeldJointDef,
	b2ComputeHull,
	b2MakeOffsetPolygon,
	b2MakeRot,
	b2MakeBox,
	b2DebugDraw,
	b2Transform,
	b2Circle,
	b2Body_SetTransform,
	b2Body_GetPosition,
	b2Body_GetShapes,
	b2Body_SetLinearVelocity,
	b2Body_SetAngularVelocity,
	b2Body_GetLocalPoint,
	b2Body_SetType,
	b2CreateWeldJoint,
	b2DestroyJoint,
	b2Vec2,
	pxm,
	pxmVec2,
	b2World_Draw,
} = PhaserBox2D;

export const { CreateDebugDraw } = PhaserBox2DDebug;